### ISSUE TITLE
I need hyperlink 

### ISSUE THREAD

**Issue by wogho** [myogeshchavan97/bookmark-manager#1]
![image](https://user-images.githubusercontent.com/83626074/117279785-0613ee00-ae9d-11eb-9b07-820101a08fb2.png)

not click URL need hyperlink
help please

**Comment by myogeshchavan97** [comment]
@dnldp55  you can make the URL as a hyperlink If you want but as this is not an issue, I'm closing this ticket

**Comment by wogho** [comment]
Can you teach me how to make a hyperlink?

2021년 5월 7일 (금) 오후 2:58, Yogesh Chavan ***@***.***>님이 작성:

**Comment by myogeshchavan97** [comment]
@dnldp55 using the following code inside the `BookmarkItem.js` file:

```js
<div className="url">
  <strong>URL: </strong>
  <a href={url} target="_blank">
    {url}
  </a>
</div>
```

**Comment by wogho** [comment]
thank you so much 
have nice good day

**Comment by dnldp55** [comment]
who to set flex-wrap in tag ../components/Header.js
[image: image.png]

2021년 5월 7일 (금) 오후 4:10, Yogesh Chavan ***@***.***>님이 작성:
